name: Integrate NTQQ
on:
  push:
    tags:
      - 'v*'
jobs:
  build-and-release:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: 下载 NTQQ 29456
        run: Invoke-WebRequest -Uri "https://dldir1.qq.com/qqfile/qq/QQNT/Windows/QQ_9.9.16_241112_x64_01.exe" -OutFile NTQQ.exe

      - name: 静默安装 QQ
        run: .\NTQQ.exe /S
      - name: 验证安装路径
        shell: pwsh
        run: |
          $path = "C:\Program Files\Tencent\QQNT\"
          if (Test-Path $path) {
          Write-Output "路径存在"
          Get-ChildItem $path -Recurse
          } else {
          Write-Error "路径不存在"
          }

      - name: 创建 LiteloaderQQNT 启动脚本
        shell: pwsh
        run: |
          $targetPath = "C:\Program Files\Tencent\QQNT\versions\9.9.16-29456\resources\app\app_launcher\llqqnt.js"
          $content = 'require(".\LiteloaderQQNT");'
          Set-Content -Path $targetPath -Value $content -Force

      - name: 修改 package.json
        shell: pwsh
        run: |
          $packagePath = "C:\Program Files\Tencent\QQNT\versions\9.9.16-29456\resources\app\package.json"
          $json = Get-Content $packagePath | ConvertFrom-Json
          $json.main = "./app_launcher/llqqnt.js"
          $json | ConvertTo-Json -Depth 10 | Set-Content $packagePath -Force

      - name: 下载 LiteloaderQQNT
        run: Invoke-WebRequest -Uri "https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/releases/download/1.2.3/LiteLoaderQQNT.zip" -OutFile LiteLoaderQQNT.zip

      - name: 解压 LiteloaderQQNT
        run: Expand-Archive -Path LiteLoaderQQNT.zip -DestinationPath "C:\Program Files\Tencent\QQNT\versions\9.9.16-29456\resources\app\app_launcher\LiteLoaderQQNT"

      - name: 下载 dbghelp.dll
        run: Invoke-WebRequest -Uri "https://github.com/LiteLoaderQQNT/QQNTFileVerifyPatch/releases/download/DllHijack_1.1.2/dbghelp_x64.dll" -OutFile "C:\Program Files\Tencent\QQNT\dbghelp.dll"

      - name: 压缩 QQNT 文件夹
        shell: pwsh
        run: |
          $sourceDir = "C:\Program Files\Tencent\QQNT"
          $zipPath = "QQ整合包_Windows.zip"
          Compress-Archive -Path $sourceDir -DestinationPath $zipPath -Force

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependenies
        run: |
          export ELECTRON_SKIP_BINARY_DOWNLOAD=1
          npm install

      - name: Build
        run: npm run build

      - name: Compress
        run: |
          sudo apt install zip -y
          cd ./dist/
          zip -r ../LLOneBot.zip ./*

      - name: Extract version from tag
        id: get-version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> "$GITHUB_OUTPUT"

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'LLOneBot.zip, QQ整合包_Windows.zip'
          draft: true
          token: ${{ secrets.RELEASE_TOKEN }}
          name: LLOneBot v${{ steps.get-version.outputs.VERSION }}
